theme: jekyll-theme-cayman
title: Romani Keyboard (IRU Standard)
description: A free IRU standard Romani keyboard layout for Windows and MacOSX
show_downloads: true
logo: /images/logo.png
github:
  win_url: Romani_IRU_Windows.zip
  mac_url: Romani_IRU_Mac.dmg
